// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKT5EcOSzph1VzQrR3vo-ucyqULkYej-A',
    appId: '1:702911420242:web:b2e0fe0fd3bd7fc6074c8b',
    messagingSenderId: '702911420242',
    projectId: 'mdu-ward-connect',
    authDomain: 'mdu-ward-connect.firebaseapp.com',
    databaseURL: 'https://mdu-ward-connect-default-rtdb.firebaseio.com',
    storageBucket: 'mdu-ward-connect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVonSd4sa_3cr4sWDEVzM0q87kbQgE4Co',
    appId: '1:702911420242:android:4f8565eb4bb0bbd4074c8b',
    messagingSenderId: '702911420242',
    projectId: 'mdu-ward-connect',
    databaseURL: 'https://mdu-ward-connect-default-rtdb.firebaseio.com',
    storageBucket: 'mdu-ward-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsqXz4iYYtSVxjwXZZIE0MQSwJ7qu6M3M',
    appId: '1:702911420242:ios:3269158a9c9bc970074c8b',
    messagingSenderId: '702911420242',
    projectId: 'mdu-ward-connect',
    databaseURL: 'https://mdu-ward-connect-default-rtdb.firebaseio.com',
    storageBucket: 'mdu-ward-connect.appspot.com',
    androidClientId: '702911420242-e894406p0q62a5g7ljv5dj874oip27hr.apps.googleusercontent.com',
    iosClientId: '702911420242-f58tkplreacui1ahash4qht7g7oo928a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mduAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsqXz4iYYtSVxjwXZZIE0MQSwJ7qu6M3M',
    appId: '1:702911420242:ios:791c130e81bbcd88074c8b',
    messagingSenderId: '702911420242',
    projectId: 'mdu-ward-connect',
    databaseURL: 'https://mdu-ward-connect-default-rtdb.firebaseio.com',
    storageBucket: 'mdu-ward-connect.appspot.com',
    androidClientId: '702911420242-e894406p0q62a5g7ljv5dj874oip27hr.apps.googleusercontent.com',
    iosClientId: '702911420242-oc076pud1ove4s199r8qe4033f1fhsao.apps.googleusercontent.com',
    iosBundleId: 'com.example.mduAdmin.RunnerTests',
  );
}
